system:
  addr: 8080
logger:
  level: "debug"
  writeInFile: true
  writeInConsole: true
logFile:
  filePath: "gin.log"
  maxsize: 100
  maxAge: 30
  maxBackup: 10
  compress: true
jwt:
  secret: "secret"
  expired: 86400

db:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Luchen1122"
  name: "test"
  params: "charset=utf8&parseTime=True&loc=Local"
